language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lekan123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lekan123/react-test npm run test

after_success:
  - docker build -t lekan123/multi-client ./client
  - docker build -t lekan123/multi-nginx ./nginx
  - docker build -t lekan123/multi-server ./server
  - docker build -t lekan123/multi-worker ./worker
  # Login to docker CLI
  - docker login -u "$DOCKERID" -p "$DOCKER_TOKEN" docker.io
  # take those images and push them to the docker hub
  - docker push lekan123/multi-client
  - docker push lekan123/multi-nginx
  - docker push lekan123/multi-server
  - docker push lekan123/multi-worker
